# Generated by Django 2.0.4 on 2018-04-20 10:43

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendedpage',
            name='content',
        ),
        migrations.AddField(
            model_name='extendedpage',
            name='body',
            field=wagtail.core.fields.StreamField((('heading_block', wagtail.core.blocks.CharBlock(classname='full title')), ('text_block', wagtail.core.blocks.RichTextBlock()), ('image_block', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Embetten externer Inhalte wie Viedeos.', icon='media'))), blank=True, verbose_name='Page Body'),
        ),
    ]
