# Generated by Django 2.0.4 on 2018-04-24 09:12

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20180423_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedpage',
            name='body',
            field=wagtail.core.fields.StreamField((('heading_block', wagtail.core.blocks.StructBlock((('heading_text', wagtail.core.blocks.CharBlock(classname='title', required=True)), ('level', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a header size'), ('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], required=False))))), ('text_block', wagtail.core.blocks.RichTextBlock()), ('image_block', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Einbetten externer Inhalte wie Viedeos.', icon='media')), ('columns', wagtail.core.blocks.StreamBlock((('column_block', wagtail.core.blocks.StructBlock((('max_width', wagtail.core.blocks.IntegerBlock(required=False)), ('body', wagtail.core.blocks.StreamBlock((('heading_block', wagtail.core.blocks.StructBlock((('heading_text', wagtail.core.blocks.CharBlock(classname='title', required=True)), ('level', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a header size'), ('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], required=False))))), ('text_block', wagtail.core.blocks.RichTextBlock()), ('image_block', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Einbetten externer Inhalte wie Viedeos.', icon='media')))))))),)))), blank=True, verbose_name='Page Body'),
        ),
    ]
