# Generated by Django 2.0.4 on 2018-04-27 11:52

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20180427_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedpage',
            name='body',
            field=wagtail.core.fields.StreamField((('heading_block', wagtail.core.blocks.StructBlock((('heading_text', wagtail.core.blocks.CharBlock(classname='title', required=True)), ('level', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a header size'), ('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], required=False))))), ('text_block', wagtail.core.blocks.RichTextBlock()), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Einbetten externer Inhalte wie Viedeos.', icon='media')), ('link_block', wagtail.core.blocks.StructBlock((('Url', wagtail.core.blocks.URLBlock()), ('Page', wagtail.core.blocks.PageChooserBlock())))), ('image_block', wagtail.core.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('caption', wagtail.core.blocks.CharBlock(classname='caption', required=True)), ('description', wagtail.core.blocks.TextBlock(classname='description')), ('author', wagtail.core.blocks.CharBlock(classname='author', required=True)), ('license', wagtail.core.blocks.CharBlock(classname='license', required=True)), ('link', wagtail.core.blocks.StructBlock((('Url', wagtail.core.blocks.URLBlock()), ('Page', wagtail.core.blocks.PageChooserBlock()))))))), ('columns', wagtail.core.blocks.StreamBlock((('column_block', wagtail.core.blocks.StructBlock((('max_width', wagtail.core.blocks.IntegerBlock(required=False)), ('body', wagtail.core.blocks.StreamBlock((('heading_block', wagtail.core.blocks.StructBlock((('heading_text', wagtail.core.blocks.CharBlock(classname='title', required=True)), ('level', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a header size'), ('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], required=False))))), ('text_block', wagtail.core.blocks.RichTextBlock()), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Einbetten externer Inhalte wie Viedeos.', icon='media')), ('link_block', wagtail.core.blocks.StructBlock((('Url', wagtail.core.blocks.URLBlock()), ('Page', wagtail.core.blocks.PageChooserBlock())))), ('image_block', wagtail.core.blocks.StructBlock((('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('caption', wagtail.core.blocks.CharBlock(classname='caption', required=True)), ('description', wagtail.core.blocks.TextBlock(classname='description')), ('author', wagtail.core.blocks.CharBlock(classname='author', required=True)), ('license', wagtail.core.blocks.CharBlock(classname='license', required=True)), ('link', wagtail.core.blocks.StructBlock((('Url', wagtail.core.blocks.URLBlock()), ('Page', wagtail.core.blocks.PageChooserBlock()))))))))))))),)))), blank=True, verbose_name='Page Body'),
        ),
    ]
